# Kapitel 4: NumPy-Grundlagen
McKinney, W. (2017). *Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython*. 2. Auflage. Sebastopol, CA [u. a.]: O’Reilly.

**Überarbeitet durch armin.baenziger@zhaw.ch. Letzte Anpassung: 13.01.2020**

- NumPy, kurz für Numerical Python, ist ein zentrales Packet für numerische Berechnungen in Python.
- In diesem Kapitel werden **Arrays** und das Konzept der **"Vektorisierung"** eingeführt.
- Da Pandas auf NumPy aufbaut, sind Grundlagenkenntnisse in NumPy hilfreich.

In [ ]:
%autosave 0

## NumPys Ndarray: Ein mehrdimensionales Array-Objekt
Zuerst laden wir die NumPy-Bibliothek mit der üblichen Abkürzung np:

In [1]:
import numpy as np

- Eine wichtige Datenstruktur in NumPy ist der N-dimensionale Array, oder **`ndarray`**, welcher ein schneller, flexibler Container für grosse Datensets in Python ist.
- Es folgt ein Beispiel von einem Ndarray:

In [5]:
arr1 = np.array([[6, 3, 5], [3, 2, 4]])
arr1

array([[6, 3, 5],
       [3, 2, 4]])

`arr1` ist *zwei*dimensional. In der Datenanalyse sind ein- und zweidimensionale Arrays üblich.

In [6]:
arr1.ndim     # Dimension des Array

2

In [7]:
arr1.shape    # arr1 hat zwei Zeilen und drei Spalten

(2, 3)

- **Mit Arrays können mathematische Operationen auf ganze Datenblöcke angewendet werden.** 
- **Die Syntax ist dabei ähnlich wie bei den entsprechenden Operationen zwischen Skalaren.**
- Beispiel:

In [8]:
arr1 + 3    

array([[9, 6, 8],
       [6, 5, 7]])

In [9]:
arr1 * 10

array([[60, 30, 50],
       [30, 20, 40]])

Ein `ndarray` ist ein *multidimensionaler* Container für *homogene* Daten (Daten vom gleichen Typ).

In [10]:
arr1.dtype    # Datentyp im Array

dtype('int32')

### Ndarrays erstellen

Listen können mit der Funktion `array` einfach in Arrays umgewandelt werden.

In [11]:
liste1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(liste1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
arr1.ndim   # eindimensionaler Array (Vektor)

1

In [13]:
liste2 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(liste2)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr2.ndim    # Zweidimensionaler Array (Matrix)

2

In [15]:
arr2.shape   # Atribut shape: Der Array hat 3 Zeilen und 4 Spalten. 

(3, 4)

Mit der Methode `reshape` kann ein Array in eine neue Form gebracht werden.

In [16]:
arr2.reshape((2,6))  # in 2x6-Array umwandeln

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

#### Spezielle Arrays erstellen:

Die np-Funktion `arrange` entspricht der `range`-Funktion in Core-Python.

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(-3, 12, 2)   # von -3 bis unter 12 mit Schritt von 2

array([-3, -1,  1,  3,  5,  7,  9, 11])

In [19]:
np.arange(101, 113).reshape(2,6)

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112]])

Arrays mit lauter Nullen erstellen:

In [ ]:
arr1_zeros = np.zeros(10)
arr1_zeros

In [ ]:
arr2_zeros = np.zeros((2,5))
arr2_zeros

Arrays mit lauter Einsen erstellen:

In [ ]:
np.ones((3, 6))

Anlegung eines Arrays ohne speziellen Inhalt (Container für später hinzuzufügenden Inhalt):

In [ ]:
container = np.empty((2, 5))
container
# Achtung: empty liefert nicht unbedingt nur 0, sondern 
# uninitialisierten "Müll".

**Kontrollfragen:**

In [ ]:
# Gegeben: 
array1 = np.array([3, 4, 1, 0, 2, 2])
array1

In [ ]:
# Frage 1: Was ist der Output?
array1.ndim

In [ ]:
# Frage 2: Erzeugen Sie aus dem Array "array1" den Array 
# "array2" mit drei Zeilen und zwei Spalten. Verwenden Sie
# hierzu die Methode reshape().


In [ ]:
# Frage 3: Was ist der Output?
array2.shape

### Mehr zur Arithmetik mit NumPy-Arrays
- Arrays sind wichtig, weil man mit ihnen viele Batch-Operationen ohne `for`-Loops umsetzen kann. Man spricht von *Vektorisierung (vectorization)*.
- Arithmetische Operationen zwischen Arrays mit gleichen Dimensionen (bzw. Shape ist identisch) führen dazu, dass die Operationen **elementweise** durchgeführt werden.

In [ ]:
# Gegeben:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

In [ ]:
# Gegeben:
arr2 = np.array([[0, 2, 1], [1, 0, 3]])
arr2

In [ ]:
arr1 + arr2   # elementweise Addition

In [ ]:
arr1 ** arr2  # elementweise Potenz

Operationen mit einem Skalar ("einzelner Wert") führen dazu, dass der Skalar auf jedes Element des Arrays übertragen wird. Man spricht von *"Broadcasting"*.

In [ ]:
arr1 * 1.1

In [ ]:
arr1 ** 0.5  # Quadratwurzel aller Elemente

Elementweise Multiplikation:

In [ ]:
arr1 * arr2

Hinweis für diejenigen, die sich mit linearer Algebra auskennen: Die eigentliche Matrixmultiplikation wird mit `np.dot()` oder `@` umgesetzt.

**Kontrollfragen:**

In [ ]:
# Gegeben: 
arr1

In [ ]:
# Gegeben:
arr2

In [ ]:
# Frage 1: Was ist der Output?
arr1.shape

In [ ]:
# Frage 2: Was ist der Output?
arr1 - 3

In [ ]:
# Frage 3: Was ist der Output?
arr2 * 3

In [ ]:
# Frage 4: Was ist der Output?
arr1 - arr2

### Grundlegende Indexierung und Slicing
Zur Erinnerung: Python beginnt die Indexierung mit 0 (1. Wert in der Sequenz).

In [ ]:
arr = np.arange(10, 20)
arr

In [ ]:
arr[5]  # Indexierung wie gewohnt

In [ ]:
arr[-1] # Letzter Wert der Sequenz

In [ ]:
arr[:3]  # Slicing wie gewohnt

In [ ]:
arr[5:8] 

In [ ]:
arr[5:8] = 0   
arr

Ein wichtiger Unterschied zwischen (built-in) Python-Listen und NumPy-Arrays liegt darin, dass Array-Sclices **Views** (und keine Kopie) auf den Original-Array darstellen.

In [ ]:
arr_slice = arr[5:8]
arr_slice

In [ ]:
arr_slice[1] = 999
arr               # Auch das Original wurde verändert!

Will man explizit eine Kopie (und keinen View), muss man die `copy`-Methode verwenden.

In [ ]:
arr_slice = arr[5:8].copy()
arr_slice[1] = 1000
arr_slice

In [ ]:
arr         # Das Original wurde nun nicht verändert!

#### Indexierung und Slicing bei Arrays mit höheren Dimensionen
Zwei Dimensionen

In [ ]:
arr2d = np.arange(9).reshape(3,3)
arr2d

In [ ]:
arr2d[2]        # 3. Zeile (Index 2)

In [ ]:
arr2d[0][1]     # Rekursive Indexierung: 1. Zeile, 2. Spalte

In [ ]:
arr2d[0, 1]     # Zweite Möglichkeit: 1. Zeile, 2. Spalte

Bei zweidimensionalen Arrays (Matrizen) gilt der Merksatz: **Zeilen zuerst, Spalten später**

In [ ]:
arr2d[2,:]      # Alternative zu arr2d[2]

In [ ]:
arr2d[:,1]      # 2. Spalte auswählen

In [ ]:
arr2d[:2, 1:] # Die ersten zwei Zeilen und ab zweiter Spalte

In [ ]:
arr2d[1, :2]  # Zweite Zeile und die ersten zwei Spalten

In [ ]:
arr2d[:2, 2]

In [ ]:
arr2d[:2, 1:] = 0
arr2d

**Kontrollfragen:**

In [ ]:
# Gegeben: 
array3 = np.arange(11,20).reshape(3,3)
array3

In [ ]:
# Frage 1: Was ist der Output?
array3[1,2]

In [ ]:
# Frage 2: Was ist der Output?
array3[:2]

In [ ]:
# Frage 3: Was ist der Output?
array3[:2, 1:]

### Advanced Indexing
Darunter fallen boolsche Indexierung und Ganzzahlindexierung.
#### Boolsche Indixierung

Grundsätzlicher Mechanismus:

In [21]:
x = np.array([21, -7, 19, -2, 0])
x

array([21, -7, 19, -2,  0])

In [22]:
bool_arr = np.array([True, True, False, True, False])
bool_arr

array([ True,  True, False,  True, False])

In [23]:
x[bool_arr]   
# Diejenigen Werte von x werden ausgewählt, an deren Stelle True steht.

array([21, -7, -2])

Üblicherweise generieren wir den boolschen Array über eine Bedingung:

In [24]:
bool_arr = (x > 0) 
bool_arr

array([ True, False,  True, False, False])

In [25]:
x[bool_arr] # Alle x-Werte grösser 0

array([21, 19])

In [26]:
x[x > 0]    # Man kann die Bedingung auch direkt übergeben.

array([21, 19])

Weitere Beispiele:

In [27]:
zivilstand = np.array(['ledig', 'geschieden', 'verheiratet', 'ledig'])

In [28]:
alter = np.array([27, 55, 35, 18])

In [29]:
ist_ledig = (zivilstand == 'ledig')  # boolscher Array

In [30]:
alter[ist_ledig]     # Alter von ledigen Personen

array([27, 18])

In [31]:
# Es ginge auch direkt:
alter[zivilstand == 'ledig']

array([27, 18])

In [32]:
alter[ist_ledig][0]  # Alter der ersten ledigen Person

27

In [33]:
alter[zivilstand != 'ledig']     # Alter von nicht ledigen Personen

array([55, 35])

In [34]:
alter[~(zivilstand == 'ledig')] # geht auch so

array([55, 35])

Der Operator "**`~`**" ist sehr hilfreich, um einen (bereits erstellten) boolschen Array zu invertieren. 

In [37]:
alter[~ist_ledig]    # Das Alter aller Personen, die NICHT ledig sind.

array([55, 35])

Bedingungen können auch kombiniert werden:

In [38]:
auswahl = (zivilstand == 'ledig') | (zivilstand == 'geschieden')
auswahl

array([ True,  True, False,  True])

In [39]:
alter[auswahl]

array([27, 55, 18])

- Die Schlüsselwörter `and` und `or` funktionieren nicht mit boolschen Arrays. Man benützt `&` (und) und `|` (oder).
- Boolsche Indexierung funktioniert auch für Arrays höherer Dimension: 

In [40]:
data = np.array([[9, -2], [7, 0], [-4, 1]])
data

array([[ 9, -2],
       [ 7,  0],
       [-4,  1]])

In [41]:
auswahl = [True, False, True]

In [42]:
data[auswahl]  # erste Zeile ja, zweite nein, dritte ja

array([[ 9, -2],
       [-4,  1]])

In [43]:
data < 0     # welche Elemente sind negativ?

array([[False,  True],
       [False, False],
       [ True, False]])

In [44]:
data[data < 0]     # negative Elemente auswählen

array([-2, -4])

In [45]:
data[data < 0] = 0 # Alle negativen Werte mit 0 ersetzen.
data

array([[9, 0],
       [7, 0],
       [0, 1]])

**Kontrollfragen:**

In [46]:
# Gegeben: 
print('array1:', array1)
array2 = np.array(list('abcdef'))
print('array2:', array2)

NameError: name 'array1' is not defined

In [ ]:
# Frage 1: Was ist der Output?
array2[[True, False, True, False, False, False]]

In [ ]:
# Frage 2: Was ist der Output?
array2[array1 == 2]

In [ ]:
# Frage 3: Was ist der Output?
array2[array1 > 0]

In [ ]:
# Frage 4: Was ist der Output?
array1[(array2 == 'b') | (array2 == 'f')]

#### Ganzzahlindexierung (Integer Indexing, auch Fancy Indexing)
*Fancy Indexing* ist ein NumPy-Begriff für das Indexieren mit Ganzzahlen-Arrays.

In [ ]:
# Beispieldaten:
array2

In [ ]:
array2[0]   # erster Wert (Repetition)

In [ ]:
# Auswahl von mehreren Werten mit gewünschter Reihenfolge:
array2[[0, 2, 1, 0]]

Beachten Sie, dass eine Liste (zwischen den eckigen Klammern) übergeben wird und dass auch Elemente wiederholt ausgewählt werden können.

In [ ]:
# Weitere Beispieldaten:
arr = np.arange(5*3).reshape((5, 3))
arr

In [ ]:
arr[0]   # Repetition: Auswahl der ersten Zeile

In [ ]:
arr[0,:]   # es geht auch so (erste Zeile und alle Spalten)

In [ ]:
# Auswahl von mehreren Zeilen mit gewünschter Reihenfolge:
arr[[3, 0, 3]]  # Die Zeile 3 (vierte) wird zweimal ausgewählt!

In [ ]:
arr[-1]  # letzte Zeile

In [ ]:
arr[:,[0,2]]     # alle Zeilen und Spalten 0 und 2 auswählen

- *Hinweis:* "Advanced Indexing" erstellt *eine Kopie der Daten*, selbst wenn der zurückgegebene Array unverändert ist (während Slicing einen View auf die Originaldaten erstellt).

**Kontrollfragen:**

In [ ]:
# Gegeben: 
array2

In [ ]:
# Frage 1: Was ist der Output?
array2[[0, 0, 1]]

In [ ]:
# Frage 2: Was ist der Output?
array2[[-1, -3]]

### Arrays transponieren
Wir beschränken uns hier auf Arrays mit zwei Dimensionen bzw. Matrizen.

In [ ]:
arr = np.arange(4*2).reshape((4, 2))
arr

In [ ]:
# Zeilen werden zu Spalten und umgekehrt:
arr.transpose()   # Transpose-Methode

In [ ]:
arr.T           # kürzer mit Transpose-Attribut

## Universal Functions
Eine "Ufunc" ist eine Funktion, welche ***elementweise*** Operationen auf *Ndarrays* ausführt.

In [ ]:
arr = np.arange(5)
arr

In [ ]:
np.sqrt(arr)            # Quadratwurzel von jedem Element

In [ ]:
np.sqrt(arr).round(3)     # auf 3 Nachkommastellen gerundet

In [ ]:
np.exp(arr).round(3)    # Exponentialfunktion

Binary Ufuncs (Ufuncs auf *zwei* Arrays)

In [ ]:
x = np.array([1, 2, 5])
y = np.array([3, -7, 0])
np.maximum(x, y)   
# Nimmt jeweils das Maximum von x und y pro Indexposistion

## Array-basiertes Programmieren
- Viele Datenverarbeitungsaufgaben können statt mit Loops mit kurzen Array-Ausdrücken umgesetzt werden. 
- Man spricht von *Vektorisierung*. 
- Die Vektorisierung führt dazu, dass Operationen viel schneller ausgeführt werden als mit Loops. 
- **Einfaches Beispiel**: Die Werte von zwei Listen sollen posisitionsbezogen zusammenaddiert werden und in einer dritten Liste abgespeichert werden.

In [ ]:
# Gegeben:
list1 = [1, 5, -1, 0, 3]
list2 = [2, 3, 0, -2, 6]

Man könnte einen for-Loop oder eine List-Comprehension zur Lösung nutzen. Einfacher geht es mit NumPy-Arrays: 

In [ ]:
arr1 = np.array(list1)
arr2 = np.array(list2)

arr3 = arr1 + arr2
arr3   # oder list(arr3), falls eine Liste verlangt ist

### Bedingungen als Array-Operationen formulieren
Angenommen wir haben zwei Werte-Arrays und einen boolschen Array:

In [ ]:
cond = np.array([True, False, True, True, False])
print('arr1:', arr1)
print('arr2:', arr2)
print('cond:', cond)

Es soll nun ein Wert von `arr1` genommen werden, wenn der entsprechende Wert in `cond` `True` ist, ansonsten soll der Wert von `arr2` stammen.

Am einfachsten setzt man hierzu auf die Funktion `np.where`, welche der Excel-Funktion `WENN` gleicht.

In [ ]:
result = np.where(cond, arr1, arr2)
result

Weitere Beispiele, wie man `where` einsetzen kann bei Datenanalysen:

In [ ]:
np.where(arr1 > arr2, arr1, arr2)  
# Nimmt jeweils den grösseren (oder gleich grossen) Wert der beiden Arrays.

**Kontrollfrage:**

In [ ]:
# Frage: Was ist der Output?
np.where([True, False, True], [1, 2, 3], [10, 20, 30])

### Mathematische und statistische Methoden
- Mit NumPy können (Quasi-) Zufallszahlen (aus verschiedenen Verteilungen) generiert werden. 
- Wenn wir "Zufallszahlen" generieren, können wir einen sogenannten Seed setzten, damit wir reproduzierbare Ergebnisse erhalten (immer die gleichen Werte).

In [47]:
np.random.seed(327) 
# Dadurch erhalten wir immer die gleichen "Zufallszahlen".
# In der Klammer kann auch eine andere natürliche Zahl 
# zwischen 0 und 2**32 - 1 stehen!

In [48]:
arr = np.random.randn(2,3) # Standardnormaverteilte Zufallsvariablen
arr

array([[ 1.71562172, -0.3980736 , -0.29765049],
       [-1.7918477 ,  0.97713881,  1.16761162]])

In [49]:
# Beispieldaten:
arr = np.random.randint(1, 7, 12)  
# randint zieht ganze Zahlen, hier zwischen 1 bis (exklusiv) 7.
# Damit lässt sich z. B. (wie hier) ein Würfelsimulator erstellen.

arr    # 12 Würfelrealisationen

array([2, 1, 3, 4, 1, 4, 2, 6, 6, 2, 6, 2])

Sogenannte *Aggregationen* (oder *Reduktionen*), wie `sum` (Summe), `mean` (arithm. Mittelwert) oder `var` (Varianz) kann man entweder als Methode oder np-Funktion aufrufen:

In [ ]:
arr.sum()

In [ ]:
np.sum(arr)

In [ ]:
np.mean(arr)

Die Aggregation kann über *alle* Werte des Arrays geschehen oder *entlang von Achsen* (Zeilen / Spalten).

In [50]:
# Beispieldaten:
np.random.seed(99)
arr = np.random.randint(0, 4, (3,4))
arr

array([[1, 3, 1, 0],
       [1, 0, 2, 0],
       [1, 0, 1, 3]])

In [ ]:
arr.sum()        
# arithmetisches Mittel aller Werte im Array arr

In [53]:
arr.sum(axis=0)  
# Aggregation entlang von Zeilen (also Spaltenmittelwerte)

array([3, 3, 4, 3])

In [54]:
arr.sum(axis=1)   
# Aggregation entlang von Spalten (also Zeilenmittelwerte) 

array([5, 3, 5])

In [55]:
arr.mean(axis=1)  # Mittelwerte pro Zeile

array([1.25, 0.75, 1.25])

Andere Methoden, wie `cumsum` und `cumpord`, aggregieren nicht sondern erzeugen einen neuen Array mit kumulierten Werten.

In [67]:
arr2 = np.array([[101, 1, 3, 2, -1], [0, 55551, 3, 2, -1]])
arr2.cumsum()
# Resultat: [0, 0+1, 0+1+3, 0+1+3+2, 0+1+3+2-1]

array([  101,   102,   105,   107,   106,   106, 55657, 55660, 55662,
       55661], dtype=int32)

**Kontrollfragen:**

In [68]:
# Gegeben: 
arr

array([[1, 3, 1, 0],
       [1, 0, 2, 0],
       [1, 0, 1, 3]])

In [70]:
# Frage 1: Wie erhalten wir die drei Spaltensummen von arr3.
arr.sum(axis=0)

array([3, 3, 4, 3])

In [71]:
# Frage 2: Was erzeugt die folgende Anweisung?
np.array([2, 3, 1, 0]).cumsum()

array([2, 5, 6, 6], dtype=int32)

### Methoden für boolsche Arrays

In [72]:
# Vorbemerkung: True wird als 1 und False als 0 gerechnet:
True + False + True

2

In [ ]:
boolarray = np.array([True, False, True, False])
boolarray.sum()   # Anzahl True

In [ ]:
boolarray.any()    # Mindestens ein True?

In [ ]:
boolarray.all()      # Sind alle True?

In [ ]:
# Zur Erinnerung:
arr2

In [ ]:
arr2 > 0            # Welche Elemente sind positiv?

In [ ]:
(arr2 > 0).sum()   # Anzahl positiver Werte

In [ ]:
print(arr1)
print(arr2)

In [ ]:
# Ist an mind. einer Stelle arr1 grösser als arr2?
(arr1 > arr2).any()

**Kontrollfragen:**

In [ ]:
# Gegeben: 
arr

In [ ]:
# Frage 1: Was ist der Output?
(arr >= 3).sum()

In [ ]:
# Frage 2: Was ist der Output?
(arr == 0).mean()  

In [ ]:
# Frage: Was ist der Output?
(arr == 0).any()

### Sortieren

In [ ]:
# Ausgangslage:
arr2 = np.array([ 0,  1,  3,  2, -1])

In [ ]:
sorted(arr2)   # arr2 bleibt erhalten.

In [ ]:
arr2

In [ ]:
np.sort(arr2)  # arr2 bleibt erhalten.

In [ ]:
arr2

In [ ]:
arr2.sort()    # Sortierung ist permanent.
arr2

Hinweis: Die Methode `sort` sortiert *inplace*. Die Funktion `np.sort` erstellt hingegen eine Kopie.

### Mengenoperationen
Oft will man wissen, welche (oder auch wie viele) einzigartige Werte (unique values) vorhanden sind. 

In [73]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [74]:
# Lösung mit Python-Grundfunktionen:
set(names)

{'Bob', 'Joe', 'Will'}

In [75]:
# Anzahl unterschiedlicher Namen im Array names.
len(np.unique(names))

3

## Dateien einlesen und speichern

Da wir später Datensätze nur in Pandas einlesen und speichern, werden wir diesen Abschnitt im Lehrmittel nicht behandeln.

## Lineare Algebra
Wird in diesem Kurs ebenfalls nicht thematisiert.

## (Pseudo-) Zufallszahlengenerator
Zuvor haben wir bereits (ad hoc) Zufallszahlen mit NumPy erstellt. Es folgt ein Überblick und einige Ergänzungen

Für die Reproduzierbarkeit von Resultaten kann ein Seed gesetzt werden: 

In [ ]:
np.random.seed(987)

In [76]:
# Standardnormalverteilte Zufallsvariablen:
np.random.randn(3,2)

array([[-0.15462185, -0.06903086],
       [ 0.75518049,  0.82564665],
       [-0.11306921, -2.36783759]])

In [77]:
# Alternative Funktion, die noch zusätzliche Argumente kennt:
np.random.normal(loc=5, scale=2, size=(3, 2))
# Normalverteilte Zufallsvariablen mit Mittelwert 5 und 
# Standardabweichung 2 in einem 3x2-Array.

array([[4.66590113, 6.37079594],
       [5.04700022, 5.91240256],
       [5.54098556, 2.12998371]])

In [78]:
# Uniformverteilung [0, 1):
np.random.rand(2, 3)

array([[0.29226912, 0.81614236, 0.82804257],
       [0.22157737, 0.6448347 , 0.09518162]])

In [79]:
# Diskrete Uniformverteilung:
np.random.randint(1, 7, (3, 4))  # z. B. Würfelaugen

array([[6, 5, 1, 5],
       [6, 4, 2, 5],
       [4, 3, 4, 6]])

Im Lehrmittel werden weitere Funktionen vorgestellt, die wir aber im Kurs nicht benötigen.

**Kontrollfragen:**

In [82]:
# Aufgabe 1: Erstellen Sie den Vektor z mit 5 Realisationen aus einer 
# Standardnormalverteilung.
np.random.randn(5)

array([-2.13970379,  0.86132265,  1.7002844 , -0.5287848 ,  1.76347792])

In [83]:
# Aufgabe 2: Erstellen Sie den Vektor z mit 1000 Realisationen aus einer 
# Uniformverteilung (zwischen 0 und 1). 
# Ermitteln Sie danach den Mittelwert von z.
np.random.rand(1000).mean()

0.5204005588898064

## Fazit
- Während der Rest des Kurses sich darauf konzentriert, mit **Pandas** Data-Wrangling-Skills zu entwickeln, werden wir weiterhin mit einem ähnlichen Array-basierten Stil arbeiten. 
- In Anhang A des Lehrmittels werden weiterführende NumPy-Kenntnisse vermittelt, auf die wir im Kurs nicht eingehen können.